---
version: '3'
services:
  asterisk:
    image: alexshander/asterisk:13.37.0
    container_name: asterisk
    restart: always
    networks:
      dockervlan:
        ipv4_address: 192.168.14.16
    logging:
      driver: "json-file"
      options:
        max-size: "100M"
        max-file: "3"

networks:
  dockervlan:
    driver: null
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: "192.168.14.0/24"
          ip_range: "192.168.14.16/32"
          gateway: "192.168.14.1"

  dockervlan:
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: "192.168.14.0/24"
          ip_range: "192.168.14.16/32"
          gateway: "192.168.14.1"
